# Generated by Django 3.2.16 on 2022-11-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fremmode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Medlem', models.IntegerField()),
                ('State', models.IntegerField()),
                ('Reason', models.IntegerField()),
            ],
            options={
                'db_table': 'Fremmode',
            },
        ),
        migrations.CreateModel(
            name='Medlemmer',
            fields=[
                ('Medlemsnummer', models.IntegerField(primary_key=True, serialize=False)),
                ('Status', models.IntegerField()),
                ('Fornavn', models.CharField(max_length=50)),
                ('Efternavn', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobil', models.CharField(max_length=12)),
                ('Text', models.CharField(max_length=100)),
                ('Onsdag', models.IntegerField()),
                ('BetalingsDato', models.DateField()),
                ('Lordag', models.IntegerField()),
                ('Tirsdag', models.IntegerField()),
            ],
            options={
                'db_table': 'medlemmer',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateID', models.IntegerField()),
                ('State', models.CharField(max_length=20)),
                ('HandOvertext', models.CharField(max_length=30)),
                ('Image', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'States',
            },
        ),
    ]
